### ISSUE TITLE
Can you build for iOS?

### ISSUE THREAD

**Issue by kiwi07** [Phisto/CoreAudioConverter#1]

**Comment by Phisto** [comment]
i think its possibly to build lame for ios ... but so far i never needed to.
the framework as it is will not support ios ...

**Comment by kiwi07** [comment]
Hi,

Please help me to get it work for iOS because I would like to develop a converter for iPhone and iPad.
Thanks

**Comment by Phisto** [comment]
hey,
im not an expert with ios development so i cant really help you with advice, but there are some projects on github you could check out. 
just google "lame for ios" to find them :)

as for a framework around lame ... there are considerable differences between an iphone and a macbook so i dont think it would benefit this project if i would add ios as a target.

**Comment by kiwi07** [comment]
thank you for your support.
